"""Shared helpers for GeoTagCopy PyInstaller build scripts."""

from __future__ import annotations

import hashlib
import os
import subprocess
import sys
import tarfile
import urllib.request
import zipfile
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
APP_NAME = "GeoTagCopy"
ENTRYPOINT = PROJECT_ROOT / "geotagcopy" / "__main__.py"
BUILD_INFO = PROJECT_ROOT / "geotagcopy" / "_build_info.py"
EXIFTOOL_VERSION = "13.57"
ICON_ICO = PROJECT_ROOT / "assets" / "icon" / "icon.ico"


def pyinstaller_available() -> bool:
    result = subprocess.run(
        [sys.executable, "-m", "PyInstaller", "--version"],
        cwd=PROJECT_ROOT,
        capture_output=True,
        text=True,
    )
    return result.returncode == 0


def write_build_info(script_name: str) -> None:
    support_url = os.environ.get("GEOTAGCOPY_SUPPORT_URL", "").strip()
    if not support_url:
        BUILD_INFO.unlink(missing_ok=True)
        return

    BUILD_INFO.write_text(
        f"# Generated by {script_name}. Do not edit.\n"
        f"SUPPORT_URL = {support_url!r}\n",
        encoding="utf-8",
    )


def base_pyinstaller_command() -> list[str]:
    return [
        sys.executable,
        "-m",
        "PyInstaller",
        "--noconfirm",
        "--name",
        APP_NAME,
        "--collect-data",
        "customtkinter",
        "--collect-data",
        "imageio_ffmpeg",
        "--collect-submodules",
        "pillow_heif",
        "--hidden-import",
        "PIL._tkinter_finder",
    ]


def download_file(url: str, destination: Path) -> None:
    urllib.request.urlretrieve(url, destination)


def verify_sha256(path: Path, expected_sha256: str) -> None:
    digest = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            digest.update(chunk)

    actual_sha256 = digest.hexdigest()
    if actual_sha256 != expected_sha256:
        raise RuntimeError(
            f"Checksum mismatch for {path.name}: expected {expected_sha256}, "
            f"got {actual_sha256}"
        )


def safe_extract_tar(archive_path: Path, destination: Path) -> None:
    destination = destination.resolve()
    with tarfile.open(archive_path, "r:gz") as archive:
        for member in archive.getmembers():
            target = (destination / member.name).resolve()
            if destination != target and destination not in target.parents:
                raise RuntimeError(f"Unsafe path in archive: {member.name}")
            if member.islnk() or member.issym():
                raise RuntimeError(f"Unsupported link in archive: {member.name}")

        archive.extractall(destination)


def safe_extract_zip(archive_path: Path, destination: Path) -> None:
    destination = destination.resolve()
    with zipfile.ZipFile(archive_path) as archive:
        for member in archive.infolist():
            target = (destination / member.filename).resolve()
            if destination != target and destination not in target.parents:
                raise RuntimeError(f"Unsafe path in archive: {member.filename}")

        archive.extractall(destination)
