#!/usr/bin/env python3
"""Build macOS GeoTagCopy artifacts with PyInstaller."""

from __future__ import annotations

import argparse
import hashlib
import os
import platform
import shutil
import subprocess
import sys
import tarfile
import tempfile
import urllib.request
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
APP_NAME = "GeoTagCopy"
BUNDLE_IDENTIFIER = "com.geotagcopy.app"
ENTRYPOINT = PROJECT_ROOT / "geotagcopy" / "__main__.py"
BUILD_INFO = PROJECT_ROOT / "geotagcopy" / "_build_info.py"
VENDORED_EXIFTOOL = PROJECT_ROOT / "vendor" / "exiftool"
EXIFTOOL_VERSION = "13.57"
EXIFTOOL_ARCHIVE_NAME = f"Image-ExifTool-{EXIFTOOL_VERSION}.tar.gz"
EXIFTOOL_ARCHIVE_URL = (
    f"https://sourceforge.net/projects/exiftool/files/{EXIFTOOL_ARCHIVE_NAME}/download"
)
EXIFTOOL_ARCHIVE_SHA256 = (
    "58f74f5cf84350693a00c4df236fd4810e5abaf25fab2d15eaa9dcc4872d4481"
)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Build GeoTagCopy as a macOS .app bundle or one-file executable."
    )
    parser.add_argument(
        "--target",
        choices=("app", "onefile", "all"),
        default="app",
        help="Build target. Default: app",
    )
    parser.add_argument(
        "--no-clean",
        action="store_true",
        help="Keep PyInstaller caches between builds.",
    )
    parser.add_argument(
        "--no-bundle-exiftool",
        action="store_true",
        help="Skip downloading and bundling ExifTool.",
    )
    args = parser.parse_args()

    if platform.system() != "Darwin":
        print("This builder must run on macOS to produce macOS artifacts.", file=sys.stderr)
        return 2

    if not _pyinstaller_available():
        print(
            "PyInstaller is not installed. Run: python3 -m pip install -r requirements-build.txt",
            file=sys.stderr,
        )
        return 2

    if not args.no_bundle_exiftool:
        _ensure_vendored_exiftool()

    _write_build_info()

    targets = ("app", "onefile") if args.target == "all" else (args.target,)
    for target in targets:
        _run_pyinstaller(target=target, clean=not args.no_clean)

    _print_artifacts(targets)
    return 0


def _pyinstaller_available() -> bool:
    result = subprocess.run(
        [sys.executable, "-m", "PyInstaller", "--version"],
        cwd=PROJECT_ROOT,
        capture_output=True,
        text=True,
    )
    return result.returncode == 0


def _write_build_info() -> None:
    payment_link = os.environ.get("GEOTAGCOPY_STRIPE_PAYMENT_LINK", "").strip()
    if not payment_link:
        BUILD_INFO.unlink(missing_ok=True)
        return

    BUILD_INFO.write_text(
        "# Generated by scripts/build_macos.py. Do not edit.\n"
        f"STRIPE_PAYMENT_LINK = {payment_link!r}\n",
        encoding="utf-8",
    )


def _run_pyinstaller(target: str, clean: bool) -> None:
    cmd = [
        sys.executable,
        "-m",
        "PyInstaller",
        "--noconfirm",
        "--name",
        APP_NAME,
        "--osx-bundle-identifier",
        BUNDLE_IDENTIFIER,
        "--collect-data",
        "customtkinter",
        "--collect-data",
        "imageio_ffmpeg",
        "--collect-submodules",
        "pillow_heif",
        "--hidden-import",
        "PIL._tkinter_finder",
    ]

    if clean:
        cmd.append("--clean")

    if _has_vendored_exiftool():
        cmd.extend(["--add-data", f"{VENDORED_EXIFTOOL}:exiftool"])

    if target == "app":
        cmd.extend(["--windowed", "--onedir"])
    elif target == "onefile":
        cmd.append("--onefile")
    else:
        raise ValueError(f"Unsupported target: {target}")

    cmd.append(str(ENTRYPOINT))

    print(f"Building {target} target...")
    subprocess.run(cmd, cwd=PROJECT_ROOT, check=True)


def _has_vendored_exiftool() -> bool:
    return (VENDORED_EXIFTOOL / "exiftool").is_file()


def _ensure_vendored_exiftool() -> None:
    if _has_vendored_exiftool() and (VENDORED_EXIFTOOL / "lib").is_dir():
        print(f"Using bundled ExifTool from {VENDORED_EXIFTOOL}")
        return

    print(f"Downloading ExifTool {EXIFTOOL_VERSION} for app bundling...")
    VENDORED_EXIFTOOL.parent.mkdir(parents=True, exist_ok=True)

    with tempfile.TemporaryDirectory() as tmp:
        tmp_path = Path(tmp)
        archive_path = tmp_path / EXIFTOOL_ARCHIVE_NAME
        urllib.request.urlretrieve(EXIFTOOL_ARCHIVE_URL, archive_path)
        _verify_sha256(archive_path, EXIFTOOL_ARCHIVE_SHA256)

        extract_root = tmp_path / "extract"
        extract_root.mkdir()
        _safe_extract_tar(archive_path, extract_root)

        source = extract_root / f"Image-ExifTool-{EXIFTOOL_VERSION}"
        if not (source / "exiftool").is_file() or not (source / "lib").is_dir():
            raise RuntimeError(f"Unexpected ExifTool archive layout in {source}")

        shutil.rmtree(VENDORED_EXIFTOOL, ignore_errors=True)
        VENDORED_EXIFTOOL.mkdir(parents=True)
        shutil.copy2(source / "exiftool", VENDORED_EXIFTOOL / "exiftool")
        shutil.copytree(source / "lib", VENDORED_EXIFTOOL / "lib")
        (VENDORED_EXIFTOOL / "exiftool").chmod(0o755)

    print(f"Vendored ExifTool installed at {VENDORED_EXIFTOOL}")


def _verify_sha256(path: Path, expected_sha256: str) -> None:
    digest = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            digest.update(chunk)

    actual_sha256 = digest.hexdigest()
    if actual_sha256 != expected_sha256:
        raise RuntimeError(
            f"Checksum mismatch for {path.name}: expected {expected_sha256}, "
            f"got {actual_sha256}"
        )


def _safe_extract_tar(archive_path: Path, destination: Path) -> None:
    destination = destination.resolve()
    with tarfile.open(archive_path, "r:gz") as archive:
        for member in archive.getmembers():
            target = (destination / member.name).resolve()
            if destination != target and destination not in target.parents:
                raise RuntimeError(f"Unsafe path in ExifTool archive: {member.name}")
            if member.islnk() or member.issym():
                raise RuntimeError(f"Unsupported link in ExifTool archive: {member.name}")

        archive.extractall(destination)


def _print_artifacts(targets: tuple[str, ...]) -> None:
    print("\nBuild complete.")
    if "app" in targets:
        print(f"- App bundle: {PROJECT_ROOT / 'dist' / (APP_NAME + '.app')}")
    if "onefile" in targets:
        print(f"- Single executable: {PROJECT_ROOT / 'dist' / APP_NAME}")


if __name__ == "__main__":
    raise SystemExit(main())
